[package]
name = "discord_intl_message_utils"
description = "Utilities used across different crates in the intl package."
version.workspace = true
edition.workspace = true
repository.workspace = true
license = "MIT"
publish = true

[dependencies]
xxhash-rust = { workspace = true }
memchr = { workspace = true }
once_cell = { workspace = true }