#![doc = r" This module is autogenerated with `cargo xtask gen-spec-tests`. The"]
#![doc = r" source for this script lives at `xtask/src/bin/gen-spec-tests.rs`."]
use super::harness;
#[test]
fn example_227() {
    let input = "  \n\naaa\n  \n\n# aaa\n\n  ";
    let expected = "<p>aaa</p>\n<h1>aaa</h1>";
    let parsed = harness::parse(input);
    assert_eq!(expected, parsed);
}
