[workspace]
members = [
    "crates/discord_intl_allocator",
    "crates/discord_intl_database_core",
    "crates/discord_intl_database_exporter",
    "crates/discord_intl_database_js_source",
    "crates/discord_intl_database_json_source",
    "crates/discord_intl_database_service",
    "crates/discord_intl_database_types_generator",
    "crates/discord_intl_flat_json_parser",
    "crates/discord_intl_markdown",
    "crates/discord_intl_markdown_macros",
    "crates/discord_intl_markdown_syntax",
    "crates/discord_intl_message_database",
    "crates/discord_intl_message_utils",
    "crates/discord_intl_validator",
    "crates/keyless_json",
    "packages/swc-intl-message-transformer",
    "xtask",
]
resolver = "2"

[workspace.package]
# This version is automatically managed by `pnpm intl-cli eco version`.
version = "0.33.0"
edition = "2021"
repository = "https://github.com/discord/discord-intl"

[workspace.dependencies]
discord_intl_allocator = { version = "=0.33.0", path = "crates/discord_intl_allocator" }
discord_intl_database_core = { version = "=0.33.0", path = "crates/discord_intl_database_core" }
discord_intl_database_exporter = { version = "=0.33.0", path = "crates/discord_intl_database_exporter" }
discord_intl_database_js_source = { version = "=0.33.0", path = "crates/discord_intl_database_js_source" }
discord_intl_database_json_source = { version = "=0.33.0", path = "crates/discord_intl_database_json_source" }
discord_intl_database_service = { version = "=0.33.0", path = "crates/discord_intl_database_service" }
discord_intl_database_types_generator = { version = "=0.33.0", path = "./crates/discord_intl_database_types_generator" }
discord_intl_flat_json_parser = { version = "=0.33.0", path = "./crates/discord_intl_flat_json_parser" }
discord_intl_markdown = { version = "=0.33.0", path = "./crates/discord_intl_markdown" }
discord_intl_markdown_macros = { version = "=0.33.0", path = "./crates/discord_intl_markdown_macros" }
discord_intl_markdown_syntax = { version = "=0.33.0", path = "./crates/discord_intl_markdown_syntax" }
discord_intl_message_utils = { version = "=0.33.0", path = "./crates/discord_intl_message_utils" }
discord_intl_validator = { version = "=0.33.0", path = "./crates/discord_intl_validator" }
keyless_json = { version = "=0.33.0", path = "./crates/keyless_json" }

anyhow = "1"
criterion = "0.8.1"
ignore = "0.4.25"
mimalloc = { version = "0.1.48", features = ["local_dynamic_tls"] }
napi = { version = "3.7.0", features = ["error_anyhow", "serde-json"] }
napi-derive = "3.4.0"
regex = "1.11.3"
rustc-hash = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
swc_common = "19.0.0"
swc_core = "58.0.4"
thiserror = "2"
threadpool = "1.8.1"
unescape_zero_copy = "2.3.0"
unicode-xid = "0.2.6"
xxhash-rust = { version = "0.8.15", features = ["xxh64"] }
ustr = { version = "1.1.0", features = ["serde"] }
memchr = "2.7.6"
once_cell = "1.21.3"
lazy_static = "1.5.0"

# Build dependencies
napi-build = "2.3.1"

[profile.release-profiling]
inherits = "release"
codegen-units = 1
lto = true
# Optimize for performance
opt-level = 3
debug = true
strip = false
panic = "abort"


[profile.release]
codegen-units = 1
lto = true
# Optimize for performance
opt-level = 3
# Strip debug symbols
strip = "symbols"
panic = "abort"

[workspace.metadata.cross.build]
zig = "2.17"
