packages:
  - ./crates/discord_intl_message_database
  - ./crates/discord_intl_message_database/npm/*
  - ./crates/discord_intl_flat_json_parser
  - ./crates/discord_intl_flat_json_parser/npm/*
  - ./packages/*
  - ./tools
