[package]
name = "discord_intl_markdown_macros"
description = "Procedural macros for discord_intl_markdown"
version.workspace = true
edition.workspace = true
repository.workspace = true
license = "MIT"
publish = true

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1"
quote = "1"
syn = { version = "2", features = ["full"] }