/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class IntlMessagesDatabase {
  constructor()
  processDefinitionsFile(filePath: string, locale?: string | undefined | null): string
  processDefinitionsFileContent(filePath: string, content: string, locale?: string | undefined | null): string
  processAllTranslationFiles(localeMap: Record<string, string>): void
  processTranslationFile(filePath: string, locale: string): string
  processTranslationFileContent(filePath: string, locale: string, content: string): string
  getKnownLocales(): Array<string>
  getSourceFile(filePath: string): IntlSourceFile
  getAllSourceFilePaths(): Array<string>
  /**
   * Return a map of all message keys contained in the given source file, where the key of the
   * map is the hashed name and the value is the original.
   */
  getSourceFileKeyMap(filePath: string): Record<string, string>
  getMessage(key: string): unknown
  generateTypes(sourceFilePath: string, outputFilePath: string, allowNullability?: boolean | undefined | null): void
  precompile(sourcePath: string, locale: string, outputPath: string, format?: IntlCompiledMessageFormat | undefined | null): void
  precompileToBuffer(sourcePath: string, locale: string, format?: IntlCompiledMessageFormat | undefined | null): Buffer
  validateMessages(): Array<IntlDiagnostic>
}

export declare function hashMessageKey(key: string): string

export declare const enum IntlCompiledMessageFormat {
  Json = 0,
  KeylessJson = 1
}

export interface IntlDiagnostic {
  key: string
  file: string
  locale: string
  severity: string
  description: string
  help?: string
}

export interface IntlMessageMeta {
  secret: boolean
  translate: boolean
  bundleSecrets: boolean
  translationsPath: string
}

export interface IntlSourceFile {
  type: string
  file: string
  messageKeys: Array<number>
  meta: IntlMessageMeta
  locale?: number
}

export declare function isMessageDefinitionsFile(key: string): boolean

export declare function isMessageTranslationsFile(key: string): boolean

