/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class IntlMessagesDatabase {
  constructor()
  processDefinitionsFile(filePath: string): number
  processDefinitionsFileContent(filePath: string, content: string): number
  processAllTranslationFiles(localeMap: Record<string, string>): void
  processTranslationFile(filePath: string, locale: string): number
  processTranslationFileContent(filePath: string, locale: string, content: string): number
  getKnownLocales(): Array<string>
  getSourceFile(filePath: string): IntlSourceFile
  getAllSourceFilePaths(): Array<string>
  getSourceFileHashedKeys(filePath: string): string[]
  getMessage(key: string): unknown
  generateTypes(sourceFilePath: string, outputFilePath: string): void
  precompile(sourcePath: string, locale: string, outputPath: string, format?: IntlCompiledMessageFormat | undefined | null): void
  precompileToBuffer(sourcePath: string, locale: string, format?: IntlCompiledMessageFormat | undefined | null): Buffer
  validateMessages(): Array<IntlDiagnostic>
}

export declare function hashMessageKey(key: string): string

export declare const enum IntlCompiledMessageFormat {
  Json = 0,
  KeylessJson = 1
}

export interface IntlDiagnostic {
  key: string
  diagnostics: unknown
}

export interface IntlMessageMeta {
  secret: boolean
  translate: boolean
  bundleSecrets: boolean
  translationsPath: string
}

export interface IntlSourceFile {
  type: string
  file: string
  messageKeys: Array<number>
  meta: IntlMessageMeta
  locale?: number
}

export declare function isMessageDefinitionsFile(key: string): boolean

export declare function isMessageTranslationsFile(key: string): boolean

export declare function resolveSymbol(symbol: number): string | null

