[package]
name = "discord_intl_database_types_generator"
description = "TypeScript declaration file generation for discord_intl projects."
version.workspace = true
edition.workspace = true
repository.workspace = true
license = "MIT"
publish = true

[dependencies]
discord_intl_database_core = { workspace = true }
discord_intl_database_service = { workspace = true }
discord_intl_message_utils = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
sourcemap = "9.0.0"
