[package]
name = "discord_intl_database_types_generator"
version = "0.1.0"
edition = "2021"

[dependencies]
discord_intl_database_core = { workspace = true }
discord_intl_database_service = { workspace = true }
discord_intl_message_utils = { workspace = true }
rustc-hash = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
ustr = { workspace = true }
sourcemap = "9.0.0"
