use lazy_static::lazy_static;
use std::collections::{HashMap, HashSet};
lazy_static! {
    pub(super) static ref CARDINAL_PLURAL_SELECTORS: HashMap<&'static str, HashSet<&'static str>> =
        HashMap::from([
            ("af", HashSet::from(["one", "other"])),
            ("ak", HashSet::from(["one", "other"])),
            ("am", HashSet::from(["one", "other"])),
            ("an", HashSet::from(["one", "other"])),
            (
                "ar",
                HashSet::from(["few", "many", "one", "other", "two", "zero"])
            ),
            (
                "ars",
                HashSet::from(["few", "many", "one", "other", "two", "zero"])
            ),
            ("as", HashSet::from(["one", "other"])),
            ("asa", HashSet::from(["one", "other"])),
            ("ast", HashSet::from(["one", "other"])),
            ("az", HashSet::from(["one", "other"])),
            ("bal", HashSet::from(["one", "other"])),
            ("be", HashSet::from(["few", "many", "one", "other"])),
            ("bem", HashSet::from(["one", "other"])),
            ("bez", HashSet::from(["one", "other"])),
            ("bg", HashSet::from(["one", "other"])),
            ("bho", HashSet::from(["one", "other"])),
            ("blo", HashSet::from(["one", "other", "zero"])),
            ("bm", HashSet::from(["other"])),
            ("bn", HashSet::from(["one", "other"])),
            ("bo", HashSet::from(["other"])),
            ("br", HashSet::from(["few", "many", "one", "other", "two"])),
            ("brx", HashSet::from(["one", "other"])),
            ("bs", HashSet::from(["few", "one", "other"])),
            ("ca", HashSet::from(["many", "one", "other"])),
            ("ce", HashSet::from(["one", "other"])),
            ("ceb", HashSet::from(["one", "other"])),
            ("cgg", HashSet::from(["one", "other"])),
            ("chr", HashSet::from(["one", "other"])),
            ("ckb", HashSet::from(["one", "other"])),
            ("cs", HashSet::from(["few", "many", "one", "other"])),
            ("csw", HashSet::from(["one", "other"])),
            ("cv", HashSet::from(["one", "other", "zero"])),
            (
                "cy",
                HashSet::from(["few", "many", "one", "other", "two", "zero"])
            ),
            ("da", HashSet::from(["one", "other"])),
            ("de", HashSet::from(["one", "other"])),
            ("doi", HashSet::from(["one", "other"])),
            ("dsb", HashSet::from(["few", "one", "other", "two"])),
            ("dv", HashSet::from(["one", "other"])),
            ("dz", HashSet::from(["other"])),
            ("ee", HashSet::from(["one", "other"])),
            ("el", HashSet::from(["one", "other"])),
            ("en", HashSet::from(["one", "other"])),
            ("eo", HashSet::from(["one", "other"])),
            ("es", HashSet::from(["many", "one", "other"])),
            ("et", HashSet::from(["one", "other"])),
            ("eu", HashSet::from(["one", "other"])),
            ("fa", HashSet::from(["one", "other"])),
            ("ff", HashSet::from(["one", "other"])),
            ("fi", HashSet::from(["one", "other"])),
            ("fil", HashSet::from(["one", "other"])),
            ("fo", HashSet::from(["one", "other"])),
            ("fr", HashSet::from(["many", "one", "other"])),
            ("fur", HashSet::from(["one", "other"])),
            ("fy", HashSet::from(["one", "other"])),
            ("ga", HashSet::from(["few", "many", "one", "other", "two"])),
            ("gd", HashSet::from(["few", "one", "other", "two"])),
            ("gl", HashSet::from(["one", "other"])),
            ("gsw", HashSet::from(["one", "other"])),
            ("gu", HashSet::from(["one", "other"])),
            ("guw", HashSet::from(["one", "other"])),
            ("gv", HashSet::from(["few", "many", "one", "other", "two"])),
            ("ha", HashSet::from(["one", "other"])),
            ("haw", HashSet::from(["one", "other"])),
            ("he", HashSet::from(["one", "other", "two"])),
            ("hi", HashSet::from(["one", "other"])),
            ("hnj", HashSet::from(["other"])),
            ("hr", HashSet::from(["few", "one", "other"])),
            ("hsb", HashSet::from(["few", "one", "other", "two"])),
            ("hu", HashSet::from(["one", "other"])),
            ("hy", HashSet::from(["one", "other"])),
            ("ia", HashSet::from(["one", "other"])),
            ("id", HashSet::from(["other"])),
            ("ie", HashSet::from(["one", "other"])),
            ("ig", HashSet::from(["other"])),
            ("ii", HashSet::from(["other"])),
            ("in", HashSet::from(["other"])),
            ("io", HashSet::from(["one", "other"])),
            ("is", HashSet::from(["one", "other"])),
            ("it", HashSet::from(["many", "one", "other"])),
            ("iu", HashSet::from(["one", "other", "two"])),
            ("iw", HashSet::from(["one", "other", "two"])),
            ("ja", HashSet::from(["other"])),
            ("jbo", HashSet::from(["other"])),
            ("jgo", HashSet::from(["one", "other"])),
            ("ji", HashSet::from(["one", "other"])),
            ("jmc", HashSet::from(["one", "other"])),
            ("jv", HashSet::from(["other"])),
            ("jw", HashSet::from(["other"])),
            ("ka", HashSet::from(["one", "other"])),
            ("kab", HashSet::from(["one", "other"])),
            ("kaj", HashSet::from(["one", "other"])),
            ("kcg", HashSet::from(["one", "other"])),
            ("kde", HashSet::from(["other"])),
            ("kea", HashSet::from(["other"])),
            ("kk", HashSet::from(["one", "other"])),
            ("kkj", HashSet::from(["one", "other"])),
            ("kl", HashSet::from(["one", "other"])),
            ("km", HashSet::from(["other"])),
            ("kn", HashSet::from(["one", "other"])),
            ("ko", HashSet::from(["other"])),
            ("kok", HashSet::from(["one", "other"])),
            ("kok_Latn", HashSet::from(["one", "other"])),
            ("ks", HashSet::from(["one", "other"])),
            ("ksb", HashSet::from(["one", "other"])),
            ("ksh", HashSet::from(["one", "other", "zero"])),
            ("ku", HashSet::from(["one", "other"])),
            (
                "kw",
                HashSet::from(["few", "many", "one", "other", "two", "zero"])
            ),
            ("ky", HashSet::from(["one", "other"])),
            ("lag", HashSet::from(["one", "other", "zero"])),
            ("lb", HashSet::from(["one", "other"])),
            ("lg", HashSet::from(["one", "other"])),
            ("lij", HashSet::from(["one", "other"])),
            ("lkt", HashSet::from(["other"])),
            ("lld", HashSet::from(["many", "one", "other"])),
            ("ln", HashSet::from(["one", "other"])),
            ("lo", HashSet::from(["other"])),
            ("lt", HashSet::from(["few", "many", "one", "other"])),
            ("lv", HashSet::from(["one", "other", "zero"])),
            ("mas", HashSet::from(["one", "other"])),
            ("mg", HashSet::from(["one", "other"])),
            ("mgo", HashSet::from(["one", "other"])),
            ("mk", HashSet::from(["one", "other"])),
            ("ml", HashSet::from(["one", "other"])),
            ("mn", HashSet::from(["one", "other"])),
            ("mo", HashSet::from(["few", "one", "other"])),
            ("mr", HashSet::from(["one", "other"])),
            ("ms", HashSet::from(["other"])),
            ("mt", HashSet::from(["few", "many", "one", "other", "two"])),
            ("my", HashSet::from(["other"])),
            ("nah", HashSet::from(["one", "other"])),
            ("naq", HashSet::from(["one", "other", "two"])),
            ("nb", HashSet::from(["one", "other"])),
            ("nd", HashSet::from(["one", "other"])),
            ("ne", HashSet::from(["one", "other"])),
            ("nl", HashSet::from(["one", "other"])),
            ("nn", HashSet::from(["one", "other"])),
            ("nnh", HashSet::from(["one", "other"])),
            ("no", HashSet::from(["one", "other"])),
            ("nqo", HashSet::from(["other"])),
            ("nr", HashSet::from(["one", "other"])),
            ("nso", HashSet::from(["one", "other"])),
            ("ny", HashSet::from(["one", "other"])),
            ("nyn", HashSet::from(["one", "other"])),
            ("om", HashSet::from(["one", "other"])),
            ("or", HashSet::from(["one", "other"])),
            ("os", HashSet::from(["one", "other"])),
            ("osa", HashSet::from(["other"])),
            ("pa", HashSet::from(["one", "other"])),
            ("pap", HashSet::from(["one", "other"])),
            ("pcm", HashSet::from(["one", "other"])),
            ("pl", HashSet::from(["few", "many", "one", "other"])),
            ("prg", HashSet::from(["one", "other", "zero"])),
            ("ps", HashSet::from(["one", "other"])),
            ("pt", HashSet::from(["many", "one", "other"])),
            ("pt_PT", HashSet::from(["many", "one", "other"])),
            ("rm", HashSet::from(["one", "other"])),
            ("ro", HashSet::from(["few", "one", "other"])),
            ("rof", HashSet::from(["one", "other"])),
            ("root", HashSet::from(["other"])),
            ("ru", HashSet::from(["few", "many", "one", "other"])),
            ("rwk", HashSet::from(["one", "other"])),
            ("sah", HashSet::from(["other"])),
            ("saq", HashSet::from(["one", "other"])),
            ("sat", HashSet::from(["one", "other", "two"])),
            ("sc", HashSet::from(["one", "other"])),
            ("scn", HashSet::from(["many", "one", "other"])),
            ("sd", HashSet::from(["one", "other"])),
            ("sdh", HashSet::from(["one", "other"])),
            ("se", HashSet::from(["one", "other", "two"])),
            ("seh", HashSet::from(["one", "other"])),
            ("ses", HashSet::from(["other"])),
            ("sg", HashSet::from(["other"])),
            ("sgs", HashSet::from(["few", "many", "one", "other", "two"])),
            ("sh", HashSet::from(["few", "one", "other"])),
            ("shi", HashSet::from(["few", "one", "other"])),
            ("si", HashSet::from(["one", "other"])),
            ("sk", HashSet::from(["few", "many", "one", "other"])),
            ("sl", HashSet::from(["few", "one", "other", "two"])),
            ("sma", HashSet::from(["one", "other", "two"])),
            ("smi", HashSet::from(["one", "other", "two"])),
            ("smj", HashSet::from(["one", "other", "two"])),
            ("smn", HashSet::from(["one", "other", "two"])),
            ("sms", HashSet::from(["one", "other", "two"])),
            ("sn", HashSet::from(["one", "other"])),
            ("so", HashSet::from(["one", "other"])),
            ("sq", HashSet::from(["one", "other"])),
            ("sr", HashSet::from(["few", "one", "other"])),
            ("ss", HashSet::from(["one", "other"])),
            ("ssy", HashSet::from(["one", "other"])),
            ("st", HashSet::from(["one", "other"])),
            ("su", HashSet::from(["other"])),
            ("sv", HashSet::from(["one", "other"])),
            ("sw", HashSet::from(["one", "other"])),
            ("syr", HashSet::from(["one", "other"])),
            ("ta", HashSet::from(["one", "other"])),
            ("te", HashSet::from(["one", "other"])),
            ("teo", HashSet::from(["one", "other"])),
            ("th", HashSet::from(["other"])),
            ("ti", HashSet::from(["one", "other"])),
            ("tig", HashSet::from(["one", "other"])),
            ("tk", HashSet::from(["one", "other"])),
            ("tl", HashSet::from(["one", "other"])),
            ("tn", HashSet::from(["one", "other"])),
            ("to", HashSet::from(["other"])),
            ("tpi", HashSet::from(["other"])),
            ("tr", HashSet::from(["one", "other"])),
            ("ts", HashSet::from(["one", "other"])),
            ("tzm", HashSet::from(["one", "other"])),
            ("ug", HashSet::from(["one", "other"])),
            ("uk", HashSet::from(["few", "many", "one", "other"])),
            ("ur", HashSet::from(["one", "other"])),
            ("uz", HashSet::from(["one", "other"])),
            ("ve", HashSet::from(["one", "other"])),
            ("vec", HashSet::from(["many", "one", "other"])),
            ("vi", HashSet::from(["other"])),
            ("vo", HashSet::from(["one", "other"])),
            ("vun", HashSet::from(["one", "other"])),
            ("wa", HashSet::from(["one", "other"])),
            ("wae", HashSet::from(["one", "other"])),
            ("wo", HashSet::from(["other"])),
            ("xh", HashSet::from(["one", "other"])),
            ("xog", HashSet::from(["one", "other"])),
            ("yi", HashSet::from(["one", "other"])),
            ("yo", HashSet::from(["other"])),
            ("yue", HashSet::from(["other"])),
            ("zh", HashSet::from(["other"])),
            ("zu", HashSet::from(["one", "other"]))
        ]);
    pub(super) static ref ORDINAL_PLURAL_SELECTORS: HashMap<&'static str, HashSet<&'static str>> =
        HashMap::from([
            ("af", HashSet::from(["few", "other"])),
            ("am", HashSet::from(["other"])),
            ("an", HashSet::from(["other"])),
            ("ar", HashSet::from(["other"])),
            ("as", HashSet::from(["few", "many", "one", "other", "two"])),
            ("ast", HashSet::from(["other"])),
            ("az", HashSet::from(["few", "many", "one", "other"])),
            ("bal", HashSet::from(["one", "other"])),
            ("be", HashSet::from(["few", "other"])),
            (
                "bg",
                HashSet::from(["few", "many", "one", "other", "two", "zero"])
            ),
            ("blo", HashSet::from(["few", "one", "other", "zero"])),
            ("bn", HashSet::from(["few", "many", "one", "other", "two"])),
            ("bs", HashSet::from(["other"])),
            ("ca", HashSet::from(["few", "one", "other", "two"])),
            ("ce", HashSet::from(["other"])),
            ("cs", HashSet::from(["other"])),
            ("cv", HashSet::from(["other"])),
            (
                "cy",
                HashSet::from(["few", "many", "one", "other", "two", "zero"])
            ),
            ("da", HashSet::from(["other"])),
            ("de", HashSet::from(["other"])),
            ("dsb", HashSet::from(["other"])),
            ("el", HashSet::from(["other"])),
            ("en", HashSet::from(["few", "one", "other", "two"])),
            ("es", HashSet::from(["one", "other"])),
            ("et", HashSet::from(["other"])),
            ("eu", HashSet::from(["other"])),
            ("fa", HashSet::from(["other"])),
            ("fi", HashSet::from(["other"])),
            ("fil", HashSet::from(["one", "other"])),
            ("fr", HashSet::from(["one", "other"])),
            ("fy", HashSet::from(["other"])),
            ("ga", HashSet::from(["one", "other"])),
            ("gd", HashSet::from(["few", "one", "other", "two"])),
            ("gl", HashSet::from(["other"])),
            ("gsw", HashSet::from(["other"])),
            ("gu", HashSet::from(["few", "many", "one", "other", "two"])),
            ("he", HashSet::from(["other"])),
            ("hi", HashSet::from(["few", "many", "one", "other", "two"])),
            ("hr", HashSet::from(["other"])),
            ("hsb", HashSet::from(["other"])),
            ("hu", HashSet::from(["one", "other"])),
            ("hy", HashSet::from(["one", "other"])),
            ("ia", HashSet::from(["other"])),
            ("id", HashSet::from(["other"])),
            ("ie", HashSet::from(["other"])),
            ("in", HashSet::from(["other"])),
            ("is", HashSet::from(["other"])),
            ("it", HashSet::from(["many", "other"])),
            ("iw", HashSet::from(["other"])),
            ("ja", HashSet::from(["other"])),
            ("ka", HashSet::from(["many", "one", "other"])),
            ("kk", HashSet::from(["many", "other"])),
            ("km", HashSet::from(["other"])),
            ("kn", HashSet::from(["other"])),
            ("ko", HashSet::from(["other"])),
            ("kok", HashSet::from(["few", "one", "other", "two"])),
            ("kok_Latn", HashSet::from(["few", "one", "other", "two"])),
            ("kw", HashSet::from(["many", "one", "other"])),
            ("ky", HashSet::from(["other"])),
            ("lij", HashSet::from(["many", "other"])),
            ("lld", HashSet::from(["many", "other"])),
            ("lo", HashSet::from(["one", "other"])),
            ("lt", HashSet::from(["other"])),
            ("lv", HashSet::from(["other"])),
            ("mk", HashSet::from(["many", "one", "other", "two"])),
            ("ml", HashSet::from(["other"])),
            ("mn", HashSet::from(["other"])),
            ("mo", HashSet::from(["one", "other"])),
            ("mr", HashSet::from(["few", "one", "other", "two"])),
            ("ms", HashSet::from(["one", "other"])),
            ("my", HashSet::from(["other"])),
            ("nb", HashSet::from(["other"])),
            ("ne", HashSet::from(["one", "other"])),
            ("nl", HashSet::from(["other"])),
            ("no", HashSet::from(["other"])),
            ("or", HashSet::from(["few", "many", "one", "other", "two"])),
            ("pa", HashSet::from(["other"])),
            ("pl", HashSet::from(["other"])),
            ("prg", HashSet::from(["other"])),
            ("ps", HashSet::from(["other"])),
            ("pt", HashSet::from(["other"])),
            ("ro", HashSet::from(["one", "other"])),
            ("root", HashSet::from(["other"])),
            ("ru", HashSet::from(["other"])),
            ("sc", HashSet::from(["many", "other"])),
            ("scn", HashSet::from(["many", "other"])),
            ("sd", HashSet::from(["other"])),
            ("sh", HashSet::from(["other"])),
            ("si", HashSet::from(["other"])),
            ("sk", HashSet::from(["other"])),
            ("sl", HashSet::from(["other"])),
            ("sq", HashSet::from(["many", "one", "other"])),
            ("sr", HashSet::from(["other"])),
            ("sv", HashSet::from(["one", "other"])),
            ("sw", HashSet::from(["other"])),
            ("ta", HashSet::from(["other"])),
            ("te", HashSet::from(["other"])),
            ("th", HashSet::from(["other"])),
            ("tk", HashSet::from(["few", "other"])),
            ("tl", HashSet::from(["one", "other"])),
            ("tpi", HashSet::from(["other"])),
            ("tr", HashSet::from(["other"])),
            ("uk", HashSet::from(["few", "other"])),
            ("ur", HashSet::from(["other"])),
            ("uz", HashSet::from(["other"])),
            ("vec", HashSet::from(["many", "other"])),
            ("vi", HashSet::from(["one", "other"])),
            ("yue", HashSet::from(["other"])),
            ("zh", HashSet::from(["other"])),
            ("zu", HashSet::from(["other"]))
        ]);
}
