[package]
name = "discord_intl_database_core"
description = "A core database for managing intl messages, supporting CRUD for messages with attribution to their source files."
version.workspace = true
edition.workspace = true
repository.workspace = true
license = "MIT"
publish = true

[dependencies]
discord_intl_markdown = { workspace = true }
discord_intl_markdown_syntax = { workspace = true }
discord_intl_markdown_macros = { workspace = true }
discord_intl_message_utils = { workspace = true }
path-absolutize = "3.1.1"
rustc-hash = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
ustr = { workspace = true }
