# Fixes linking errors to allow `cargo test` to run for NAPI crates:
# https://github.com/napi-rs/napi-rs/issues/2130#issuecomment-2239407809
[target.'cfg(target_vendor = "apple")']
rustflags = [
    "-C",
    "link-args=-Wl,-undefined,dynamic_lookup,-no_fixup_chains",
]

[alias]
xtask = "run --package xtask --bin"