[package]
name = "discord_intl_database_json_source"
description = "discord_intl Source implemention for JSON messages files"
version.workspace = true
edition.workspace = true
repository.workspace = true
license = "MIT"
publish = true

[dependencies]
discord_intl_database_core = { workspace = true }
discord_intl_flat_json_parser = { workspace = true }
memchr = { workspace = true }