[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]

[target.aarch64-unknown-linux-musl]
linker = "aarch64-linux-musl-gcc"
rustflags = ["-C", "target-feature=-crt-static"]

[target.aarch64-apple-darwin.env]
MACOSX_DEPLOYMENT_TARGET = "11"

[target.x86_64-apple-darwin.env]
MACOSX_DEPLOYMENT_TARGET = "10.13"


# Fixes linking errors to allow `cargo test` to run:
# https://github.com/napi-rs/napi-rs/issues/2130#issuecomment-2239407809
[target.'cfg(target_vendor = "apple")']
rustflags = [
    "-C",
    "link-args=-Wl,-undefined,dynamic_lookup,-no_fixup_chains",
]