[package]
name = "intl_database_json_source"
version = "0.1.0"
edition = "2021"

[dependencies]
intl_database_core = { workspace = true }
memchr = { workspace = true }
unescape_zero_copy = { workspace = true }