#![doc = r" This module is autogenerated with `cargo xtask gen-spec-tests`. The"]
#![doc = r" source for this script lives at `xtask/src/bin/gen-spec-tests.rs`."]
use super::harness;
#[test]
fn example_327() {
    let input = "`hi`lo`";
    let expected = "<p><code>hi</code>lo`</p>";
    let parsed = harness::parse(input);
    assert_eq!(expected, parsed);
}
