#![doc = r" This module is autogenerated with `cargo xtask gen-spec-tests`. The"]
#![doc = r" source for this script lives at `xtask/src/bin/gen-spec-tests.rs`."]
use super::harness;
#[ignore]
#[test]
fn example_42() {
    let input = "- `one\n- two`";
    let expected = "<ul>\n<li>`one</li>\n<li>two`</li>\n</ul>";
    let parsed = harness::parse(input);
    assert_eq!(expected, parsed);
}
