#![doc = r" This module is autogenerated with `cargo xtask gen-spec-tests`. The"]
#![doc = r" source for this script lives at `xtask/src/bin/gen-spec-tests.rs`."]
use super::harness;
#[test]
fn example_648() {
    let input = "foo\nbaz";
    let expected = "<p>foo\nbaz</p>";
    let parsed = harness::parse(input);
    assert_eq!(expected, parsed);
}
#[test]
fn example_649() {
    let input = "foo \n baz";
    let expected = "<p>foo\nbaz</p>";
    let parsed = harness::parse(input);
    assert_eq!(expected, parsed);
}
