#![doc = r" This module is autogenerated with `cargo xtask gen-spec-tests`. The"]
#![doc = r" source for this script lives at `xtask/src/bin/gen-spec-tests.rs`."]
use super::harness;
#[test]
fn example_650() {
    let input = "hello $.;'there";
    let expected = "<p>hello $.;'there</p>";
    let parsed = harness::parse(input);
    assert_eq!(expected, parsed);
}
#[test]
fn example_651() {
    let input = "Foo χρῆν";
    let expected = "<p>Foo χρῆν</p>";
    let parsed = harness::parse(input);
    assert_eq!(expected, parsed);
}
#[test]
fn example_652() {
    let input = "Multiple     spaces";
    let expected = "<p>Multiple     spaces</p>";
    let parsed = harness::parse(input);
    assert_eq!(expected, parsed);
}
