[package]
name = "discord_intl_database_js_source"
description = "discord_intl Source implementation for JS messages files."
version.workspace = true
edition.workspace = true
repository.workspace = true
license = "MIT"
publish = true

[dependencies]
discord_intl_database_core = { workspace = true }
discord_intl_message_utils = { workspace = true }
swc_common = { workspace = true }
swc_core = { workspace = true, features = [
    "ecma_parser",
    "ecma_ast",
    "ecma_visit",
] }
memchr = { workspace = true }
