[package]
name = "keyless_json"
description = "A Serde serializer that allows well-structured JSON to be minified into keyless arrays of elements."
version.workspace = true
edition.workspace = true
repository.workspace = true
license = "MIT"
publish = true

[dependencies]
serde = { workspace = true }
itoa = "1"
ryu = "1"
thiserror = { workspace = true }