/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Message {
  key: string
  value: string
  line: number
  col: number
}

export declare function parseJson(text: string): Message[]

export declare function parseJsonFile(filePath: string): Message[]

