/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface Message {
  key: string
  value: string
  position: Position
}

export declare function parseJson(text: string): Message[]

export declare function parseJsonFile(filePath: string): Message[]

export interface Position {
  line: number
  col: number
}

