name: Build swc-intl-message-transformer

on:
  workflow_call:

jobs:
  build:
    name: Build swc-intl-message-transformer
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4

      - name: Setup Build Env
        uses: ./.github/actions/setup-build-env
        with:
          target: wasm

      - name: Build @discord/swc-intl-message-transformer
        run: |
          pnpm intl-cli swc build

      - name: Upload artifact
        id: upload-artifact
        uses: actions/upload-artifact@v4
        with:
          name: swc_intl_message_transformer.wasm
          path: packages/swc-intl-message-transformer/swc_intl_message_transformer.wasm
          if-no-files-found: error
