name: Build NAPI platform package

on:
  workflow_call:
    inputs:
      package:
        description: "Base name of the NPM package being built (no @discord, no platform name included)"
        required: true
        type: string
      crate:
        description: "Path name of the crate being built (e.g., some_crate instead of some-crate)"
        required: true
        type: string
      cli-name:
        description: "Name of the project in the intl-cli tool (e.g., rt, db, swc)"
        required: true
        type: string
      target:
        description: "Platform package name that maps to a Rust target triple."
        required: true
        type: string
      runner:
        description: "Which os/version to run this workflow on."
        required: true
        type: string

env:
  # This should ensure that the mac packages are allowed to run on all
  # supported macOS versions.
  MACOSX_DEPLOYMENT_TARGET: "10.13"
  DEBUG: "napi:*"
  XWIN_CACHE_DIR: ${{ github.workspace }}/.xwin

jobs:
  build:
    name: Build @discord/${{inputs.package}}-${{ inputs.target }}
    runs-on: ${{ inputs.runner }}
    defaults:
      run:
        shell: bash
    outputs:
      runner-labels: ${{ steps.upload-artifact.outputs.runner-labels || inputs.runner }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Build Env
        uses: ./.github/actions/setup-build-env
        with:
          runner: ${{ inputs.runner }}
          target: ${{ inputs.target }}

      - name: Build @discord/${{inputs.package}}-${{inputs.target}}
        run: |
          pnpm intl-cli ${{inputs.cli-name}} build --target ${{inputs.target}}

      - name: Upload artifact
        id: upload-artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{inputs.package}}.${{inputs.target}}.node
          path: crates/${{inputs.crate}}/npm/${{inputs.target}}/${{inputs.package}}.${{inputs.target}}.node
          if-no-files-found: error
