name: Lint Rust crates

on:
  - push
  - pull_request
  - workflow_call

jobs:
  lint-rust:
    name: Lint Rust crates
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Build Env
        uses: ./.github/actions/setup-build-env
        with:
          runner: macos-latest
          target: 'darwin-arm64'

      - name: cargo-fmt
        run: |
          cargo-fmt --all --check

      - name: Run Cargo test
        run: |
          cargo test