name: Publish canary packages

on:
  workflow_dispatch:
    inputs:
      packages:
        required: true
        type: string
        description: "Space-separated list of packages to publish"
      strict:
        required: true
        type: boolean
        description: "Strict Mode (only bump explicitly given packages)"

permissions:
  # To publish packages with provenance
  contents: write
  id-token: write

jobs:
  release:
    name: Release and Publish
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Build Env
        uses: ./.github/actions/setup-build-env
        with:
          native: false
          target: wasm

      - name: Set canary versions
        run: |
          pnpm intl-cli ecosystem version bump canary

      - name: Publish all @discord/intl-message-database* packages
        run: |
          pnpm intl-cli ecosystem publish-only ${{inputs.packages}} \
              --tag canary ${{inputs.strict && '--strict' || ''}} \
              --yes --skip-existing --no-git-checks \
              --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}